### ISSUE TITLE
Premissa

### ISSUE THREAD

**Issue by gustavol10** [silentiummm/Cattus#1]
Longe de qualquer resquício de humanidade, dois gatos acordam num mundo completamente desconhecido e perigoso. Lutando contra a nova realidade, ambos seguem o instinto de voltarem a suas famílias. Nesse mundo novo precisam buscar entender o porquê de estarem lá e como recuperar o passado que os foi perdido.

**Comment by Isabela0920** [comment]
Premissa do jogo finalizada.
