### ISSUE TITLE
O jogo ideal

### ISSUE THREAD

**Issue by Isabela0920** [silentiummm/Cattus#3]
Presos em um novo mundo, dois gatos, um de pelagem laranja e outro branco, estão em busca de respostas de como voltar para casa. Lutando contra o medo, eles precisam interagir com os seres habitados por esse lugar e decidir se embarcarão em uma missão pacifista ou egoica. 
  Baseando-se no universo criativo do artista Dr. Seuss, o jogo tem uma estética psicodélica, com ambientações criativas e obscuras, longe da realidade mundana. Os habitantes desse mundo possuem fisionomias distorcidas e fora do comum, com expressões melancólicas e sombrias.
  Os jogadores controlam os gatos, que mostram-se surpresos pela nova realidade. Sua primeira interação nesse mundo os diz que é necessário passar pelos quatro níveis para chegar no grande líder, que poderá ajudá-los em sua volta para casa. Os gatos encontrarão um dilema em cada fase, e deverão escolher entre duas formas de resolver o problema: ajudando a criatura ou utilizando a sua fraqueza para acabar com ela. Em ambos os casos, os jogadores serão recompensados com uma chave, que permitirá a entrada no próximo nível. 
  As escolhas de como resolver os problemas terão uma pontuação, que ao fim do jogo decidirá o destino dos gatos.

**Comment by gustavol10** [comment]
feito
