### ISSUE TITLE
Regras

### ISSUE THREAD

**Issue by Isabela0920** [silentiummm/Cattus#4]
-  As missões terão duas escolhas, com pontuações diferentes. A pontuação determinará o final;
-  Os gatos deverão trabalhar em conjunto para pegar os itens necessários para as missões;
-  Não é possível sair da fase sem a chave;
- Os jogadores são obrigados a conversar com os habitantes para avançar de etapa;
- Os gatos não podem sair do mapa;
- O jogo terá 4 fases;
- Os personagens poderão escolher apenas uma das duas opções propostas.

**Comment by gustavol10** [comment]
Regras feitas.
